apiVersion: v1
kind: ServiceAccount
metadata:
  name: s-kitchen
  namespace: kube-system
---
apiVersion: v1
kind: Service
metadata:
  name: s-kitchen
  namespace: kube-system
spec:
  ports:
  - name: web
    port: 80
    targetPort: 80
  selector:
    app: d-kitchen
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: d-kitchen
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: d-kitchen
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: d-kitchen
    spec:
      containers:
      - image: yuanyuexiang/kitchen:V${BUILD_NUMBER}
        name: d-kitchen
        ports:
        - containerPort: 80
          name: d-kitchen
